//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2._0.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_venta
    {
        public int id_venta { get; set; }
        public int id_producto { get; set; }
        public int cantidad_venta { get; set; }
        public System.DateTime fecha_venta { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
