//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2._0.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_inventarioEntities : DbContext
    {
        public bd_inventarioEntities()
            : base("name=bd_inventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<detalle_venta> detalle_venta { get; set; }
        public DbSet<deudore> deudores { get; set; }
        public DbSet<producto> productoes { get; set; }
        public DbSet<vendedor> vendedors { get; set; }
        public DbSet<venta> ventas { get; set; }
    }
}
