//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario2._0.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.detalle_venta = new HashSet<detalle_venta>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int stock_producto { get; set; }
        public int valor_entrada_producto { get; set; }
        public int valor_salida_producto { get; set; }
    
        public virtual ICollection<detalle_venta> detalle_venta { get; set; }
    }
}
